# Generated by Django 3.1.5 on 2022-03-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0008_jumunt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jumun_T',
        ),
    ]
