# Generated by Django 3.1.5 on 2022-03-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumun', '0009_delete_jumun_t'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jumunt',
            options={'managed': False, 'verbose_name': '주문장'},
        ),
    ]
